CREATE TABLE USER_MASTER(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD TEXT NOT NULL,
  IS_ACTIVE INT DEFAULT 0,
  ROLE VARCHAR(20) DEFAULT 'user',
  FILESIZE VARCHAR(50),
  UPLOAD_LIMIT VARCHAR(20) DEFAULT '1024',
  TOKEN VARCHAR(255),
  CREATED_ON VARCHAR(50),
  UPDATED_ON VARCHAR(50)
);